version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    pre_build:
      - pip install indexia

sphinx:
   configuration: docs/source/conf.py

python:
    install:
    - requirements: requirements.txt